import { reactive, readonly } from 'vue'
import { taskStore } from '../stores/taskStore.js'

const state = reactive({
  isDragging: false,
  sourceId: null,
  targetStatus: null,
})

let sourceEl = null
let sourceStatus = null
let pointerId = null
let startX = 0
let startY = 0
let offsetX = 0
let offsetY = 0
let floatingEl = null
let dragJustEnded = false
let clickTimer = null

function createFloating(cardEl) {
  const rect = cardEl.getBoundingClientRect()
  offsetX = startX - rect.left
  offsetY = startY - rect.top
  const clone = cardEl.cloneNode(true)
  clone.classList.add('drag-floating-card')
  clone.setAttribute('aria-hidden', 'true')
  clone.style.width = `${rect.width}px`
  clone.style.left = `${rect.left}px`
  clone.style.top = `${rect.top}px`
  document.body.appendChild(clone)
  return clone
}

function moveFloating(x, y) {
  if (!floatingEl) return
  floatingEl.style.left = `${x - offsetX}px`
  floatingEl.style.top = `${y - offsetY}px`
}

function findDropTarget(x, y) {
  const listEl = document.elementFromPoint(x, y)?.closest('.task-list')
  if (!listEl) return null
  const status = listEl.dataset.status
  if (!status) return null

  // The dragged card is hidden, so these are precisely the visible insertion anchors.
  const cards = [...listEl.querySelectorAll('[data-task-id]')]
    .filter(el => el !== sourceEl && el.getClientRects().length > 0)
  const before = cards.find(el => y < el.getBoundingClientRect().top + el.getBoundingClientRect().height / 2)
  return { status, beforeId: before?.dataset.taskId ?? null }
}

function orderedIds(status) {
  return [...taskStore.getByStatus(status)]
    .sort((a, b) => a.order - b.order || (b.createdAt > a.createdAt ? 1 : -1))
    .map(task => task.id)
}

function commitDrop(id, fromStatus, target) {
  if (!target) return
  const { status, beforeId } = target
  if (status === fromStatus) {
    const current = orderedIds(status)
    const next = current.filter(taskId => taskId !== id)
    const index = beforeId ? next.indexOf(beforeId) : next.length
    if (index < 0) return
    next.splice(index, 0, id)
    if (next.some((taskId, i) => taskId !== current[i])) taskStore.reorderColumn(status, next)
    return
  }

  if (!taskStore.updateStatus(id, status) || !beforeId) return
  const next = orderedIds(status).filter(taskId => taskId !== id)
  const index = next.indexOf(beforeId)
  if (index < 0) return
  next.splice(index, 0, id)
  taskStore.reorderColumn(status, next)
}

function cleanup() {
  window.removeEventListener('pointermove', onPointerMove)
  window.removeEventListener('pointerup', onPointerUp)
  window.removeEventListener('pointercancel', onPointerCancel)
  window.removeEventListener('keydown', onKeyDown)
  window.removeEventListener('blur', onPointerCancel)
  floatingEl?.remove()
  floatingEl = null
  sourceEl?.classList.remove('drag-source-hidden')
  sourceEl = null
  sourceStatus = null
  pointerId = null
  state.isDragging = false
  state.sourceId = null
  state.targetStatus = null
}

function suppressClick() {
  dragJustEnded = true
  clearTimeout(clickTimer)
  // A click generated by pointerup arrives before the next macrotask.
  clickTimer = setTimeout(() => { dragJustEnded = false }, 0)
}

function onPointerMove(e) {
  if (e.pointerId !== pointerId || !sourceEl) return
  if (!state.isDragging) {
    const dx = e.clientX - startX
    const dy = e.clientY - startY
    if (dx * dx + dy * dy < 25) return
    floatingEl = createFloating(sourceEl)
    state.isDragging = true
    state.sourceId = sourceEl.dataset.taskId
    sourceEl.classList.add('drag-source-hidden')
  }

  e.preventDefault()
  moveFloating(e.clientX, e.clientY)
  state.targetStatus = findDropTarget(e.clientX, e.clientY)?.status ?? null
}

function onPointerUp(e) {
  if (e.pointerId !== pointerId) return
  const wasDragging = state.isDragging
  const id = state.sourceId
  const fromStatus = sourceStatus
  const target = wasDragging ? findDropTarget(e.clientX, e.clientY) : null
  if (wasDragging) suppressClick()
  cleanup()
  if (wasDragging && id && fromStatus) commitDrop(id, fromStatus, target)
}

function onPointerCancel(e) {
  if (e?.pointerId != null && e.pointerId !== pointerId) return
  if (state.isDragging) suppressClick()
  cleanup()
}

function onKeyDown(e) {
  if (e.key === 'Escape') onPointerCancel()
}

export function useDrag() {
  function pointerDown(e, cardEl) {
    if (e.pointerType !== 'mouse' || e.button !== 0) return
    if (e.target.closest('.card-menu-btn, .touch-menu')) return
    if (sourceEl) cleanup()
    const task = taskStore.getById(cardEl.dataset.taskId)
    if (!task) return

    sourceEl = cardEl
    sourceStatus = task.status
    pointerId = e.pointerId
    startX = e.clientX
    startY = e.clientY
    window.addEventListener('pointermove', onPointerMove)
    window.addEventListener('pointerup', onPointerUp)
    window.addEventListener('pointercancel', onPointerCancel)
    window.addEventListener('keydown', onKeyDown)
    window.addEventListener('blur', onPointerCancel)
  }

  return {
    state: readonly(state),
    pointerDown,
    get dragJustEnded() { return dragJustEnded },
  }
}
